Fixing comments length.
odradev/odra-template pull request #4
Opened 2022-09-21 10:56 UTC by aleksanderziel

2022-09-21 10:58 UTC, zie1ony requested changes
Good job, but fix all the lines.

2022-09-23 06:10 UTC, zie1ony requested changes
Changes needed.

2022-09-23 06:10 UTC, zie1ony commented on README.md
>  A list of available backends can check [here](https://github.com/odradev/odra).
```suggestion
A list of available backends can check [here](https://github.com/odradev/odra#backends).
```
This links directly to the backend section.

2022-09-23 06:10 UTC, zie1ony commented on src/flipper.rs
> +        //... a constructor, we would call deploy_initial_settings() function.
What is the case with thos dots?

2022-09-23 07:49 UTC, aleksanderziel commented on src/flipper.rs
> +        //... a constructor, we would call deploy_initial_settings() function.
Corrected.

2022-09-23 07:50 UTC, aleksanderziel commented on src/flipper.rs
> +        /// To do so, Odra generate for us deploy() function.
Corrected.

2022-09-23 07:51 UTC, aleksanderziel commented on README.md
>  A list of available backends can check [here](https://github.com/odradev/odra).
Done.

2022-09-23 07:54 UTC, zie1ony approved these changes
+1

2022-09-23 07:57 UTC, merged